//(lower arm angle, higher arm angle)
//#define DEGREES_PER_COUNT 1 / (4096 / 360)
#define DEGREES_PER_COUNT 1

#define PICKUP_ANGLE_LOWER 77
#define PICKUP_ANGLE_HIGHER -26

#define HOME_ANGLE_LOWER 0
#define HOME_ANGLE_HIGHER 0

#define HUMAN_PLAYER_LOWER 26
#define HUMAN_PLAYER_HIGHER -82

#define MID_SCORE_LOWER 80
#define MID_SCORE_HIGHER -121