//(lower arm angle, higher arm angle)
//#define DEGREES_PER_COUNT 1 / (4096 / 360)
#define DEGREES_PER_COUNT 1

#define HOME_ANGLE_LOWER 0

#define HUMAN_PLAYER_LOWER LOW_ARM_FULL_DEPLOY

#define MID_SCORE_LOWER LOW_ARM_FULL_DEPLOY

#define HOME_ANGLE_HIGHER 0
#define MID_SCORE_HIGHER -148
#define HUMAN_PLAYER_HIGHER -138
