//(lower arm angle, higher arm angle)
//#define DEGREES_PER_COUNT 1 / (4096 / 360)
#define DEGREES_PER_COUNT 1

#define HOME_ANGLE_LOWER 0

#define HUMAN_PLAYER_LOWER LOW_ARM_FULL_DEPLOY

#define MID_SCORE_LOWER LOW_ARM_FULL_DEPLOY

#define LOW_SCORE_LOWER LOW_ARM_FULL_DEPLOY

#define UPPER_HUMAN_LOWER 25

#define HOME_ANGLE_HIGHER 0
#define MID_SCORE_HIGHER -154
#define HUMAN_PLAYER_HIGHER -140
#define LOW_SCORE_HIGHER -40
#define UPPER_HUMAN_HIGHER -100
