#define FEED_BUTTON 1

#define S_LEFT_DRIVE 1
#define S_RIGHT_DRIVE 1
#define ARM_MOTOR_BTN 1 
#define ARM_CAN_LOW_NUM 10
#define ARM_CAN_HIGH_NUM 11
#define ARM_LOW_DRIVE 1
#define ARM_HIGH_DRIVE 1
#define ARM_LOW_TEST_BTN 11
#define ARM_HIGH_TEST_BTN 12
#define ARM_GRAB_TEST_BTN 9
#define ARM_MOTOR_JOY_UP_TEST 5
#define ARM_MOTOR_JOY_DOWN_TEST 3
#define ARM_MOTOR_JOY_UP2_TEST 6
#define ARM_MOTOR_JOY_DOWN2_TEST 4
#define ARM_NUM_TEST Button(11)

#define JOYSTICK_SENSITIVITY 1.25
#define JOYSTICK_ROT_SENS 0.7
#define AUTO_SENS 0.9